on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Test Docker build without push
        id: dbuild
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/sauerborn-git/github-actions-test:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Hello world action step
      #  #id: hello
      #  #uses: sauerborn-git/github-actions-test@main
      #  #with:
      #  #  who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.dbuild.outputs }}"
